modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="logo.png"
authors="${mod_author}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="*"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${version_range_forge}"
	ordering="NONE"
	side="BOTH"
